### ISSUE TITLE
想做成陪聊可以怎么做呀

### ISSUE THREAD

**Issue by liangyuanpeng** [LCTT/LCBot#37]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. PHP 5.4 on nginx 1.9.1):
* Server type and version:
* Operating System and version:

## 重现步骤 (只有 bugs 需要)

1.
2.
3.
4.

## 你的环境

* 使用的版本:
* 环境名和版本信息(e.g. PHP 5.4 on nginx 1.9.1):
* 服务器类型和版本:
* 操作系统类型和版本:

**Comment by bestony** [comment]
完善ISSUE 内容。
