### ISSUE TITLE
Docker 安装出错

### ISSUE THREAD

**Issue by Jandaes** [LCTT/LCBot#38]
`docker pull osmeteor/pythonlcbot`  
命令执行出错、是需要更换仓库源吗？
![image](https://cloud.githubusercontent.com/assets/9146622/26517710/4abc3440-42d1-11e7-9fb3-206bbb81807f.png)

 提示：timeout  
我试了下载其它docker仓库、没问题的

**Comment by bestony** [comment]
换个 Docker 镜像

**Comment by Jandaes** [comment]
[https://github.com/LCTT/LCBot#docker-版本](https://github.com/LCTT/LCBot#docker-版本)  
请问下，除了这个地址、哪里可以看到其它地址呢

**Comment by bestony** [comment]
@Jandaes https://www.daocloud.io/mirror#accelerator-doc
