### ISSUE TITLE
群内添加新成员后没有欢迎词

### ISSUE THREAD

**Issue by shyboy** [LCTT/LCBot#63]
## 预期动作
关键词回复后可以拉人进去，可是进群后机器人没有说出关键词。设置只更改了管理员、群号还有私聊的对话。

还有一个就是想请问管理员怎么实现T人的功能啊，新手不太了解机器人的指令……

使用的win10，python3

**Comment by Yinr** [comment]
您的微信的语言是设成英文的么？现在只加了对中文的匹配，而且是对设置了 `group_puid` 里的群有效。
如果设置了全局静默模式（`silence_mode = True`）那也会禁用欢迎词的。

踢人的指令是：`拉黑 @xxx`，“拉黑”一词可以换为“移出”、“移除”、“踢出”，后面的 `@xxx` 为你要踢的人。
