### ISSUE TITLE
检测 PUID 设置。自动退出

### ISSUE THREAD

**Issue by bestony** [LCTT/LCBot#71]
## 预期动作
检测 PUID  设置，如果未设置puid，则退出，提示运行 export_puid.py
## 当前动作
无动作，直接退出
## 可能的解决方案
判断length

## 内容
合理的提示可以有效减少用户提问简单问题。

**Comment by Yinr** [comment]
puid 之前已经加了 try catch 异常处理，他们遇到问题的大概是旧版的代码吧...
